### PR TITLE
[BugFix] Distinct and filter string array

### PR DESCRIPTION
**Pull request by imbatony**
1. Distinct and filter string array to prevent library refreshing being blocked.

### CODE REVIEW

**Comment by xjasonlyu** [comment]
I don’t think doing so would have have any things to do with refresh blocking.

First, the jellyfin or emby server will automatically remove duplicate items from giving arrays such as genres and actors.

Plus, null is also a valid array value in C#, so it’s ok to pass as a returning value.

Let me know if I get anything wrong.

**Comment by imbatony** [comment]
As far as I know, the Jellyfin server will not automatically deal with blank array like [""] , it will still try to insert the blank item which cause a SQL exception and finally block the entire library refreshing.
Test cases:
fc2hub:1259441-3106475

**Comment by xjasonlyu** [comment]
For `[""]`, do you mean an array containing an empty string?

**Comment by xjasonlyu** [comment]
Merged, thanks!

**Pull request merged**
